config/routes.rb
Rails.application.routes.draw do
  namespace :sale do 
    resources :reports
  end
  
  namespace :warehouse do
    get 'warehouse/index'
  end
  namespace :deliveries do
    get 'supply_schema/schema'
    get 'supply_schema/stats'
    get 'priorities/index'
    resources :scheduleds
    resources :scheduled_items
  end

  namespace :tariff do
    get 'tariffs/index'
    get 'tariff/index'
  end

  namespace :task_manager do
    resources :tasks
    resources :statuses
    resources :categories
  end

  resources :app_global_constants
  resources :sales_operations
  resources :sales
  resources :autoresponsers

  require 'sidekiq_unique_jobs/web'
  mount Sidekiq::Web => '/sidekiq', at: "/sidekiq"

  # Rails.application.routes.draw do
  resources :sale_reports
  namespace :sale do
    get 'sale_reports/csv/:id', to: 'reports#report_csv', as: 'report_csv'
  end
  patch 'nms/update_price/:id', to: 'nms#update_price', as: 'update_price'

  namespace :warehouse do
    get 'warehouse/index'
  end
  namespace :deliveries do
    get 'supply_schema/schema'
    get 'priorities/index'
    resources :scheduleds
    resources :scheduled_items
  end


  namespace :nm do
    resources :nm_customer_discounts
    resources :nm_customer_discounts
    resources :nm_comperitors
    resources :nm_group_competitors
    resources :nm_group_queries
    resources :nms
    patch 'nms/update_price/:id', to: 'nms#update_price', as: 'update_price'
    post '/competitor_action/:id', to: 'nms#competitor_action', as: 'nm_competitor_action'
    post 'nm_group_queries/:id/query_item_action', to: 'nm_group_queries#query_item_action', as: 'nm_group_queries_item_action'
    get 'nm_group_queries/update_nm_positions/:nm_id', to: 'nm_group_queries#update_nm_positions', as: 'nm_group_queries_update_nm_positions'

  end
  resources :app_global_constants
  resources :sales_operations
  resources :sales
  resources :autoresponsers
  # resources :promotion_managers
  #   mount Sidekiq::Web => "/sidekiq"
  #   get "job" => "job#index"
  #   get "job/email" => "job#email"
  #   get "job/post" => "job#delayed_post"
  #   get "job/long" => "job#long"
  #   get "job/crash" => "job#crash"
  #   get "job/bulk" => "job#bulk"
  # end

  namespace :income do 
    post "income/update_box_type/:id", to: "income#update_box_type", as: "box_update"
    resources :income
    get "planned", to: "planned#index"
    get "planned/archived", to: "planned#archived"
    get "planned/show/:id", to: "planned#show", as: "planned_show"
    get "planned/delete/:id", to: "planned#delete", as: "planned_delete"
    get "planned/create", to: "planned#create", as: "planned_create"
    post "planned/update/:income_id", to: "planned#update", as: "planned_update"
  end
  namespace :project do 
    resources :project_roles
    resources :projects
    post "projects/role/change", to: "projects#role_user_on_projects_action", as: "projects_role_user_on_projects_action"
    post "projects/set_as_current_project", to: "projects#set_as_current_project", as: "set_as_current_project"
    post "projects/settings/change", to: "projects#user_settings_update", as: "user_settings_update"

  end
  
  resources :delivery_methods

  resources :comissions
  namespace :advert do 
    resources :adverts

    get 'adverts/:id/advert_update_api', to: 'adverts#update_from_api', as: 'advert_update_api'
    get 'adverts/:id/start', to: 'adverts#start', as: 'advert_start'
    # get 'adverts/:id/stop', to: 'adverts#stop', as: 'advert_stop'
    get 'adverts/:id/pause', to: 'adverts#pause', as: 'advert_pause'
    post 'advert/adverts/set_cpm/:id', to: 'adverts#set_cpm', as: 'set_cpm'
    post 'advert/adverts/set_daily_budget_max/:id', to: 'adverts#set_daily_budget_max', as: 'set_daily_budget_max'
    get 'adverts/:id/:advert_action', to: 'adverts#advert_action', as: 'advert_action'
    post 'adverts/:id/cluster/set_forced_state/:cluster_id', to: 'adverts#cluster_set_forced_state', as: 'cluster_set_forced_state'
    get 'adverts/:id/keywords/flush_excluded_keyword', to: 'adverts#flush_excluded_keyword', as: 'flush_excluded_keyword'
    get 'adverts/:id/keywords/clear_bad_keywords', to: 'adverts#clear_bad_keywords', as: 'clear_bad_keywords'

    get '/advert/render_async_cluster_stats/:id/:cluster_id', to: "adverts#render_async_cluster_stats", as: 'render_async_cluster_stats'
    #  to 'advert#render_partial_advert_clusters_async' as 'render_partial_advert_clusters_async'
    
    resources :promotion_managers
    get 'promotion_manager/:id/setup', to: 'promotion_managers#setup', as: 'promotion_manager_setup'
    get 'promotion_manager/setup_all', to: 'promotion_managers#setup_all', as: 'promotion_manager_setup_all'
    get 'promotion_manager/:id/set_status/:status', to: 'promotion_managers#set_status', as: 'promotion_manager_set_status'
  end

  resources :events
  resources :orders
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', "passwords": 'users/passwords'}
  # devise_for :users, :as => :user_session
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index", layouts: 'layouts'


  get "dashboard/stocks_history", to: "dashboard#stocks_history", layouts: 'layouts'
  get "dashboard/daily", to: "dashboard#daily", layouts: 'layouts'
  get "dashboard/trading", to: "dashboard#trading", layouts: 'layouts'
  get "dashboard/warehouse_balance", to: "dashboard#warehouse_balance", layouts: 'layouts'
  get "dashboard/stocks_planning", to: "dashboard#stocks_planning", layouts: 'layouts'
  get "dashboard/logistics_planning", to: "dashboard#logistics_planning", layouts: 'layouts'
  get "dashboard/sales_stats_by_district", to: "dashboard#sales_stats_by_district", layouts: 'layouts'
  get "dashboard/profit_by_current_stocks", to: "dashboard#profit_by_current_stocks", layouts: 'layouts'
  get "dashboard/nm_positions", to: "dashboard#nm_positions", layouts: 'layouts'
  get "dashboard/con_anal", to: "dashboard#con_anal", layouts: 'layouts'
  get "dashboard/weekly_orders", to: "dashboard#weekly_orders", layouts: 'layouts'
  get "dashboard/stocks_by_incomes", to: "dashboard#stocks_by_incomes"
  get "dashboard/nm/stats", to: "dashboard#nm_stats"



  get "scheduler/main", to: "scheduler#main", layouts: 'layouts'
  get "scheduler/task/:task_action/:id", to: "scheduler#task_action", layouts: 'layouts',  as: 'scheduler_task_action'

  # get "nms_queries/index", to: "nm_group_query#index", layouts: 'layouts'


  get "regions/regions", to: "regions#regions", layouts: 'layouts'
  get "regions/districts", to: "regions#districts", layouts: 'layouts'
  get "regions/district_warehouses", to: "regions#district_warehouses", layouts: 'layouts'

  
  #post 'nm_group_queries/:id/query_item_action', to: 'nm_group_queries#query_item_action', as: 'nm_group_queries_item_action'


  namespace :tariff do 
    resources :tariffs
    get "tariffs_active/index", to: "tariffs_active#index", layouts: 'layouts'
    get "tariffs_active/set/:id", to: "tariffs_active#set", layouts: 'layouts', as: 'tariffs_active_set'
    get "tariffs_active/unset/:id", to: "tariffs_active#unset", layouts: 'layouts', as: 'tariffs_active_unset'
  end


  get "pricing/index", to: "pricing#index", as: 'pricings'
  get "pricing/warehouses", to: "pricing#warehouses", as: 'pricing_wh'

  get "pricing/update_price/:nm_id", to: "pricing#update_price_item", as: 'pricings_update_prices_item'
  get "pricing/update_prices_all", to: "pricing#update_prices_all", as: 'pricings_update_prices_all'
  get "pricing/graph_prices_vs_sales/:nm_id", to: "pricing#graph_prices_vs_sales", as: 'pricing_price_vs_sales'
  get "pricing/graph_prices_vs_sales_data/:nm_id", to: "pricing#graph_prices_vs_sales_data", as: 'graph_prices_vs_sales_data'
  
  
end














  # 

app/models/sale.rb
module Sale
  def self.table_name_prefix
    "sale_"
  end
end

app/models/sale/report_list.rb
class Sale::ReportList < ApplicationRecord

  def self.update_list(project)
    rr_ids = Sale::Report.where(project_id: project.id).select(:realizationreport_id).distinct.pluck(:realizationreport_id)
    rr_ids.map do |rr_id|
      srl = Sale::ReportList.find_or_create_by project_id: project.id, realizationreport_id: rr_id
      sr = Sale::Report.find_by realizationreport_id: rr_id
      srl.date_from = sr.date_from
      srl.date_to = sr.date_to
      srl.create_dt = sr.create_dt
      srl.save
    end
  end
end

app/models/sales_and_orders/sale.rb
class Sale < ApplicationRecord

    def self.update_all_api(project)
        url = 'https://statistics-api.wildberries.ru/api/v1/supplier/reportDetailByPeriod'
        has_new_rows = true
        rrdid = 0
        ts_start = Time.now.beginning_of_week - 7.days
        sales_count = 0
        while has_new_rows
            response = project.api.get(url) do |req|
                req.params['rrdid'] = rrdid
                req.params['limit'] = 10000
                req.params['dateFrom'] = ts_start
                req.params['dateTo'] = ts_start + 7.days
                # ap req.params
            end
            

            if response.status == 200 
                if response.body != nil
                    sales = JSON.parse response.body
                    sales.map! do |s| 
                        s['project_id'] = project.id
                        s['uid'] = "#{s['realizationreport_id']}_#{s['rrd_id']}"
                        # ['date_from', 'date_to', 'create_dt', 'order_dt', 'sale_dt'].map do |k|
                        #   s[k] = Time.parse s[k]
                        # end
                        i = Sale.find_or_create_by uid: s['uid']
                        i.update s
                        i.save
                        s
                    end
                    ap sales.last
                    has_new_rows = false if sales == []
                    sales_count += sales.count

                    ap "Fetched #{sales.count}/#{sales_count}"
                    rrdid = sales.last['rrd_id'] if sales != []
                # Sale.insert_all sales, unique_by: ['uid']
                # , unique_by: ["uid", "id"]
            end
            else
                sleep 60
            end
        end

    end


end

app/controllers/sale/reports_controller.rb
class Sale::ReportsController < ApplicationController
  before_action :check_permissions, only: %i[ show report_csv ]

  # GET /sale_reports or /sale_reports.json
  def index
    @sale_reports = Sale::ReportList.where(project_id: current_user.project.id).order(date_from: :desc, realizationreport_id: :desc)
  end

  def report_csv
    file = Sale::Report.report_csv @rr_id
    sr = Sale::Report.find_by realizationreport_id: @rr_id
    filename = "Финотчет ВБ #{@rr_id} #{sr.date_from.strftime('%Y-%m-%d')} #{sr.date_to.strftime('%Y-%m-%d')}.csv"
    send_data file, :type => "text/plain", :filename=>filename, :disposition => 'attachment'
    # redirect_to sale_report_path @rr_id
  end

  # GET /sale_reports/1 or /sale_reports/1.json
  def show
    srs = Sale::Report.where(realizationreport_id: @rr_id )
    @operations = srs.select(:supplier_oper_name).distinct.pluck(:supplier_oper_name).sort
    @doc_type_names = srs.select(:doc_type_name).distinct.pluck(:doc_type_name).sort
    @period_start = srs.first.date_from
    @period_end = srs.first.date_to
    @item = srs.last
    @count = srs.count
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_permissions
      @rr_id = params[:id]
      @sale_report = Sale::Report.find_by(realizationreport_id: params[:id])
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.where(project_id: current_user.project_id).select("distinct realizationreport_id").distinct.pluck('realizationreport_id')
  end 

  # GET /sales/1 or /sales/1.json
  def show
    @rid = params['id']
    sales = Sale.where(project_id: current_user.project_id, realizationreport_id: @rid)
    @operations = sales.select('distinct supplier_oper_name').distinct.pluck('supplier_oper_name')
    update_operations @operations
    @sas = sales.select('distinct sa_name').distinct.pluck('sa_name')
    @by_ops = {}
    sel_text = 'sa_name, count(id), sum(ppvz_for_pay) as ppvz_for_pay, SUM(delivery_amount) as delivery_amount, SUM(delivery_rub) as delivery_rub, sum(penalty) as penalty'
    @operations.map do |op|
      @by_ops[op] = sales.where(supplier_oper_name: op).select(sel_text).group('sa_name').all
    end
    @result = {}
    sel_text = 'supplier_oper_name, count(id), sum(ppvz_for_pay) as ppvz_for_pay, SUM(delivery_amount) as delivery_amount, SUM(delivery_rub) as delivery_rub, sum(penalty) as penalty'
    # sales = Sale.where(project_id: current_user.project_id, realizationreport_id: @rid)
    @profit_global = 0.0
    @sas.map do |sa|
      nm = Nm::Nm.find_by supplier_article: sa
      @result[sa] = {'total' => 0.0, "count" => 0.0,'ops' => []}
      @result[sa]['ops'] = sales.where(sa_name: sa).select(sel_text).group('supplier_oper_name').all
      @result[sa]['ops'] = @result[sa]['ops'].map do |op|
        sop = SalesOperation.find_by name: op['supplier_oper_name']
        ['ppvz_for_pay', 'delivery_rub', 'penalty'].map do |op_name|
          if op[op_name]
            op[op_name] = op[op_name] * sop.factor 
            @result[sa]['total'] = @result[sa]['total'] + op[op_name]
          end
        end
        if op.supplier_oper_name == 'Продажа'
          @result[sa]['count'] = @result[sa]['count'] + op.count
          @result[sa]['price'] = (@result[sa]['total'] / @result[sa]['count']).round(2) 
          @result[sa]['profit'] = (@result[sa]['count'] * (@result[sa]['price'] - nm.total_cost)).round(2) 
          @profit_global += @result[sa]['profit']
        end
      op
      end
    end
    # ap @result

  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy!

    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find_by(realizationreport_id: params[:id])
      redirect_to '/' if @sale.project_id != current_user.project_id
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:date_from)
    end

    def update_operations(ops)
      ops.map do |op|
        sop = SalesOperation.find_by name: op
        if not sop
          sop = SalesOperation.new name: op
          sop.factor = -1
          sop.save
        end
      end
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sale/reports/_table.haml
.relative.overflow-x-auto
  - total_pay = sr.inject(0.0) {|s, i| s+= i.ppvz_for_pay}
  - total_pay_text = number_with_precision(total_pay , :precision => 2, :delimiter => "'") 

  - total_sales = sr.inject(0.0) {|s, i| s+= i.retail_amount}
  - total_sales_text = number_with_precision(total_sales , :precision => 2, :delimiter => "'")


  %p.py-3
    Итого сумма продаж #{total_sales_text} (retail_amount).
    %br
    Итого к перечислению за това #{total_pay_text} (ppvz_for_pay).
  %table.w-full.px-4.py-6.text-sm.text-left.rtl:text-right.text-gray-800.dark:text-gray-400
    %thead{class: "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"}
      %tr
        %td{class: "px-3 py-3"} nm_id
        %td{class: "px-3 py-3 text-right"} Сумма продаж
        %td{class: "px-3 py-3 text-right"} Штрафы
        %td{class: "px-3 py-3 text-right"} Доплаты
        %td{class: "px-3 py-3 text-right"} Возм. изд. логистики
        -# %td{class: "px-3 py-3 text-right"} РЦ
        -# %td{class: "px-3 py-3 text-right"} Цена
        %td{class: "px-3 py-3 text-right"} Кол-во
        %td{class: "px-3 py-3 text-right"} Доставок
        %td{class: "px-3 py-3 text-right"} Возвратов
        %td{class: "px-3 py-3 text-right"} Сумма логистики
        %td{class: "px-3 py-3 text-right"} К перечислению за товар
        %td{class: "px-3 py-3 text-right"} Итого к перечислению
        %td{class: "px-3 py-3 text-right"} Итого цена

    %tbody
      - sr.each do |s|
        %tr{class: 'bg-white border-b dark:bg-gray-800 dark:border-gray-700'}
          - nm = Nm::Nm.find_by nm_id: s.nm_id
          %td{class: "px-3 py-3"}
            - if nm
              %div.font-bold.whitespace-nowrap= nm.supplier_article
              %div.text-gray-400.text-sm.whitespace-nowrap= nm.object
            - else
              %div.font-bold <Артикул не найден>
              %div.text-gray-400.text-sm.nowrap= s.nm_id

          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.retail_amount , :precision => 2, :delimiter => "'") 
          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.penalty , :precision => 2, :delimiter => "'") 
          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.additional_payment , :precision => 2, :delimiter => "'") 
          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.rebill_logistic_cost , :precision => 2, :delimiter => "'") 

          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.quantity , :precision => 0, :delimiter => "'") 
          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.delivery_amount , :precision => 0, :delimiter => "'") 
          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.return_amount , :precision => 0, :delimiter => "'") 
          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.delivery_rub , :precision => 2, :delimiter => "'") 
          %td{class: "px-3 py-3 text-right font-mono"}
            = number_with_precision(s.ppvz_for_pay , :precision => 2, :delimiter => "'") 
            - total_pay += s.ppvz_for_pay

          %td{class: "px-3 py-3 text-right"} 
            - sum_total = s.ppvz_for_pay 
            - sum_total += s.rebill_logistic_cost if s.rebill_logistic_cost
            - sum_total += s.additional_payment if s.additional_payment
            - sum_total += s.penalty if s.penalty
            - sum_total += s.delivery_rub if s.delivery_rub
            
            = number_with_precision(sum_total , :precision => 2, :delimiter => "'") 
          %td{class: "px-3 py-3 text-right"} 
            - price_total = sum_total / s.quantity
            = number_with_precision(price_total , :precision => 2, :delimiter => "'") 

app/views/sale/reports/index.haml
%header{class: "bg-white  "}
  %div{class: "w-full flex flex-wrap items-center justify-between"}
    %div{class: ' px-4 py-6 sm:px-6 lg:px-8'}
      %h1{class: 'text-3xl font-bold tracking-tight text-gray-900 place-items-center self-center place-self-center justify-items-center'} Финансовые отчеты

%div{class: "mx-auto px-4 py-4 sm:px-6 md:px-24 md:pb-2 lg:px-8 lg:pb-6"}
  .relative.overflow-x-auto
    %table.w-full.px-4.py-6.text-sm.text-left.rtl:text-right.text-gray-800.dark:text-gray-400
      %thead{class: "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"}
        %tr
          %th{class: "px-3 py-3 text-left"} Номер недели
          %th{class: "px-3 py-3"} Номер отчета
          %th{class: "px-3 py-3 text-right"} Дата отчета начало
          %th{class: "px-3 py-3 text-right"} Дата отчета конец
          %th{class: "px-3 py-3 text-right"} Дата формирования

      %tbody
        - @sale_reports.each do |s|
          %tr{class: 'bg-white border-b dark:bg-gray-800 dark:border-gray-700'}
            %td{class: "px-3 py-3 text-left"}= s.date_from.strftime('%-V')
            %td{class: "px-3 py-3"}= link_to s.realizationreport_id, sale_report_path(id: s.realizationreport_id), class: 'text-blue-400'
            %td{class: "px-3 py-3 text-right"}= s.date_from
            
            %td{class: "px-3 py-3 text-right"}= s.date_to
            %td{class: "px-3 py-3 text-right"}= s.create_dt
            

app/views/sale/reports/show.haml
%header{class: "bg-white  "}
  %div{class: "w-full flex flex-wrap items-center justify-between"}
    %div{class: ' px-4 py-6 sm:px-6 lg:px-8'}
      %h1{class: 'text-3xl font-bold tracking-tight text-gray-900 place-items-center self-center place-self-center justify-items-center'} Финансовый отчет #{@rr_id}
      %h2{class: 'text-xl  tracking-tight text-gray-900 place-items-center self-center place-self-center justify-items-center'} c #{@period_start.strftime('%d.%m.%Y')} по #{@period_end.strftime('%d.%m.%Y')}
      %div{class: 'text-small  tracking-tight text-gray-500 place-items-center self-center place-self-center justify-items-center'} Количество записей #{@count}
    %div{class:' px-4 py-6'}
      %div{class: 'inline-flex rounded-md'}
        = link_to "Загрузить сводку", sale_report_csv_path(id: @rr_id), class: "px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white"

%div{class: "mx-auto px-4 py-4 sm:px-6 md:px-24 md:pb-2 lg:px-8 lg:pb-6"}
  %h1.text-2xl.font-bold.pb-1 Сводка
  - sr = Sale::Report.report(@rr_id, nil, nil)
  = render "sale/reports/table", sr: sr, op: nil, dt: nil

- @doc_type_names.each do |dt|
  %div{class: "mx-auto px-4 py-4 sm:px-6 md:px-24 md:pb-2 lg:px-8 lg:pb-6"}

        
    %h1.text-2xl.font-bold.pb-1 Тип операции: #{ dt != "" ? dt : "<Без имени>"}
    - @operations.each do |op|
      - sr = Sale::Report.report(@rr_id, dt, op)
      - if sr.any?
        %h1.text-xl.font-bold.text-gray-700.pb-3 Операция: #{ op != "" ? op : "<Без имени>"}
        = render "sale/reports/table", sr: sr, op: op, dt: dt 
        