config/routes.rb
Rails.application.routes.draw do
  namespace :sale do 
    resources :reports
  end
  
  namespace :warehouse do
    get 'warehouse/index'
  end
  namespace :deliveries do
    get 'supply_schema/schema'
    get 'supply_schema/stats'
    get 'priorities/index'
    resources :scheduleds
    resources :scheduled_items
  end

  namespace :tariff do
    get 'tariffs/index'
    get 'tariff/index'
  end

  namespace :task_manager do
    resources :tasks
    resources :statuses
    resources :categories
  end

  resources :app_global_constants
  resources :sales_operations
  resources :sales
  resources :autoresponsers

  require 'sidekiq_unique_jobs/web'
  mount Sidekiq::Web => '/sidekiq', at: "/sidekiq"

  # Rails.application.routes.draw do
  resources :sale_reports
  namespace :sale do
    get 'sale_reports/csv/:id', to: 'reports#report_csv', as: 'report_csv'
  end
  patch 'nms/update_price/:id', to: 'nms#update_price', as: 'update_price'

  namespace :warehouse do
    get 'warehouse/index'
  end
  namespace :deliveries do
    get 'supply_schema/schema'
    get 'priorities/index'
    resources :scheduleds
    resources :scheduled_items
  end


  namespace :nm do
    resources :nm_customer_discounts
    resources :nm_customer_discounts
    resources :nm_comperitors
    resources :nm_group_competitors
    resources :nm_group_queries
    resources :nms
    patch 'nms/update_price/:id', to: 'nms#update_price', as: 'update_price'
    post '/competitor_action/:id', to: 'nms#competitor_action', as: 'nm_competitor_action'
    post 'nm_group_queries/:id/query_item_action', to: 'nm_group_queries#query_item_action', as: 'nm_group_queries_item_action'
    get 'nm_group_queries/update_nm_positions/:nm_id', to: 'nm_group_queries#update_nm_positions', as: 'nm_group_queries_update_nm_positions'

  end
  resources :app_global_constants
  resources :sales_operations
  resources :sales
  resources :autoresponsers
  # resources :promotion_managers
  #   mount Sidekiq::Web => "/sidekiq"
  #   get "job" => "job#index"
  #   get "job/email" => "job#email"
  #   get "job/post" => "job#delayed_post"
  #   get "job/long" => "job#long"
  #   get "job/crash" => "job#crash"
  #   get "job/bulk" => "job#bulk"
  # end

  namespace :income do 
    post "income/update_box_type/:id", to: "income#update_box_type", as: "box_update"
    resources :income
    get "planned", to: "planned#index"
    get "planned/archived", to: "planned#archived"
    get "planned/show/:id", to: "planned#show", as: "planned_show"
    get "planned/delete/:id", to: "planned#delete", as: "planned_delete"
    get "planned/create", to: "planned#create", as: "planned_create"
    post "planned/update/:income_id", to: "planned#update", as: "planned_update"
  end
  namespace :project do 
    resources :project_roles
    resources :projects
    post "projects/role/change", to: "projects#role_user_on_projects_action", as: "projects_role_user_on_projects_action"
    post "projects/set_as_current_project", to: "projects#set_as_current_project", as: "set_as_current_project"
    post "projects/settings/change", to: "projects#user_settings_update", as: "user_settings_update"

  end
  
  resources :delivery_methods

  resources :comissions
  namespace :advert do 
    resources :adverts

    get 'adverts/:id/advert_update_api', to: 'adverts#update_from_api', as: 'advert_update_api'
    get 'adverts/:id/start', to: 'adverts#start', as: 'advert_start'
    # get 'adverts/:id/stop', to: 'adverts#stop', as: 'advert_stop'
    get 'adverts/:id/pause', to: 'adverts#pause', as: 'advert_pause'
    post 'advert/adverts/set_cpm/:id', to: 'adverts#set_cpm', as: 'set_cpm'
    post 'advert/adverts/set_daily_budget_max/:id', to: 'adverts#set_daily_budget_max', as: 'set_daily_budget_max'
    get 'adverts/:id/:advert_action', to: 'adverts#advert_action', as: 'advert_action'
    post 'adverts/:id/cluster/set_forced_state/:cluster_id', to: 'adverts#cluster_set_forced_state', as: 'cluster_set_forced_state'
    get 'adverts/:id/keywords/flush_excluded_keyword', to: 'adverts#flush_excluded_keyword', as: 'flush_excluded_keyword'
    get 'adverts/:id/keywords/clear_bad_keywords', to: 'adverts#clear_bad_keywords', as: 'clear_bad_keywords'

    get '/advert/render_async_cluster_stats/:id/:cluster_id', to: "adverts#render_async_cluster_stats", as: 'render_async_cluster_stats'
    #  to 'advert#render_partial_advert_clusters_async' as 'render_partial_advert_clusters_async'
    
    resources :promotion_managers
    get 'promotion_manager/:id/setup', to: 'promotion_managers#setup', as: 'promotion_manager_setup'
    get 'promotion_manager/setup_all', to: 'promotion_managers#setup_all', as: 'promotion_manager_setup_all'
    get 'promotion_manager/:id/set_status/:status', to: 'promotion_managers#set_status', as: 'promotion_manager_set_status'
  end

  resources :events
  resources :orders
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', "passwords": 'users/passwords'}
  # devise_for :users, :as => :user_session
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index", layouts: 'layouts'


  get "dashboard/stocks_history", to: "dashboard#stocks_history", layouts: 'layouts'
  get "dashboard/daily", to: "dashboard#daily", layouts: 'layouts'
  get "dashboard/trading", to: "dashboard#trading", layouts: 'layouts'
  get "dashboard/warehouse_balance", to: "dashboard#warehouse_balance", layouts: 'layouts'
  get "dashboard/stocks_planning", to: "dashboard#stocks_planning", layouts: 'layouts'
  get "dashboard/logistics_planning", to: "dashboard#logistics_planning", layouts: 'layouts'
  get "dashboard/sales_stats_by_district", to: "dashboard#sales_stats_by_district", layouts: 'layouts'
  get "dashboard/profit_by_current_stocks", to: "dashboard#profit_by_current_stocks", layouts: 'layouts'
  get "dashboard/nm_positions", to: "dashboard#nm_positions", layouts: 'layouts'
  get "dashboard/con_anal", to: "dashboard#con_anal", layouts: 'layouts'
  get "dashboard/weekly_orders", to: "dashboard#weekly_orders", layouts: 'layouts'
  get "dashboard/stocks_by_incomes", to: "dashboard#stocks_by_incomes"
  get "dashboard/nm/stats", to: "dashboard#nm_stats"



  get "scheduler/main", to: "scheduler#main", layouts: 'layouts'
  get "scheduler/task/:task_action/:id", to: "scheduler#task_action", layouts: 'layouts',  as: 'scheduler_task_action'

  # get "nms_queries/index", to: "nm_group_query#index", layouts: 'layouts'


  get "regions/regions", to: "regions#regions", layouts: 'layouts'
  get "regions/districts", to: "regions#districts", layouts: 'layouts'
  get "regions/district_warehouses", to: "regions#district_warehouses", layouts: 'layouts'

  
  #post 'nm_group_queries/:id/query_item_action', to: 'nm_group_queries#query_item_action', as: 'nm_group_queries_item_action'


  namespace :tariff do 
    resources :tariffs
    get "tariffs_active/index", to: "tariffs_active#index", layouts: 'layouts'
    get "tariffs_active/set/:id", to: "tariffs_active#set", layouts: 'layouts', as: 'tariffs_active_set'
    get "tariffs_active/unset/:id", to: "tariffs_active#unset", layouts: 'layouts', as: 'tariffs_active_unset'
  end


  get "pricing/index", to: "pricing#index", as: 'pricings'
  get "pricing/warehouses", to: "pricing#warehouses", as: 'pricing_wh'

  get "pricing/update_price/:nm_id", to: "pricing#update_price_item", as: 'pricings_update_prices_item'
  get "pricing/update_prices_all", to: "pricing#update_prices_all", as: 'pricings_update_prices_all'
  get "pricing/graph_prices_vs_sales/:nm_id", to: "pricing#graph_prices_vs_sales", as: 'pricing_price_vs_sales'
  get "pricing/graph_prices_vs_sales_data/:nm_id", to: "pricing#graph_prices_vs_sales_data", as: 'graph_prices_vs_sales_data'
  
  
end














  # 

app/controllers/scheduler_controller.rb
class SchedulerController < ApplicationController

	def main
		if current_user.id == 1
			@tasks = ScheduleTemplate.order(:name).all
		else
			@tasks = ScheduleTemplate.order(:name).where(only_admin: false).all
		end
		@tasks = @tasks.map do |template|
			# task = task_find_or_create_by template
			# task = task_find_or_create_by template
			# ap task
			{
				"template" => template,
				"task" => get_task_by_template(template)
			}
		end

    if current_user.id == 1
  		@jobs = Sidekiq::Cron::Job.all 
  		@jobs.map do |j|
  			if j.args[0] == 1
  				# ap j.args
  				j.destroy
  			end
  		end
			@jobs = @jobs.sort_by {|i| i.name}
    end

	end
 
	def task_action
		# WbUpdateAdvertsStatsJob.perform_inline(current_user.project_id)
		template = ScheduleTemplate.find_by(id: params[:id])
		has_access = true

		if template.only_admin == true
			has_access = current_user.id == 1
		else 
			has_access = true
		end
		# ap has_access
		# ap template
		if template and has_access
			task = task_find_or_create_by template
			# ap task
			case params[:task_action]
			when 'enable'
				task.enable!
				event_ui "#{template.name} Задача поставлена в план"
			when 'disable'
				task.destroy
				event_ui "#{template.name} Задача удалена из очереди"
			when 'enque'
				task.enque!
				event_ui "#{template.name} Задача запущена"
			end
		end
		redirect_to scheduler_main_path
	end

	private

	def task_find_or_create_by(template)
		task = get_task_by_template template
		if task == nil
			name = template.only_one ? template.name : "#{template.name} #{current_user.project_id}"
			if template.period_minute >= 24*60
				period = "every #{template.period_minute/60}d"
			elsif template.period_minute >=60 and template.period_minute < 24*60 
				period = "every #{template.period_minute/60}h"
			else
				period = "every #{template.period_minute}m"
			end
			# if template.only_one then source = 'schedule' else source = 'dynamic' end
			source = 'schedule'
			job = Sidekiq::Cron::Job.create(source: source, name: name, cron: period, class: template.job_name, args: current_user.project_id, status: 'disabled', queue: template.queue)

			task = get_task_by_template template
			ap task
		end
		return task
	end

	def get_task_by_template(template) 
		Sidekiq::Cron::Job.all.find {|i| i.klass == template.job_name and i.args[0] == current_user.project_id }
		
	end

		
end

app/views/scheduler/main.haml
%header{class: "bg-white  "}
  %div{class: "w-full flex flex-wrap items-center justify-between"}
    %div{class: ' px-4 py-6 sm:px-6 lg:px-8'}
      %h1{class: 'text-3xl font-bold tracking-tight text-gray-900 place-items-center self-center place-self-center justify-items-center'} Планировщик заданий

%div{class: "mx-auto px-4 py-4 md:pb-2 lg:px-8 "}
  %h2{class: 'text-xl mb-2 font-bold tracking-tight text-gray-900 place-items-center self-center place-self-center justify-items-center'} Регламентные задания текущего проекта
  .relative.overflow-x-auto
    %table.w-full.px-4.py-6.text-sm.text-left.rtl:text-right.text-gray-800.dark:text-gray-400

      %thead{class: "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"}
        %tr
          %th{scope: "col", class: "px-6 py-3"} Артикул
          %th{scope: "col", class: "px-6 py-3"} Название
          %th{scope: "col", class: "px-6 py-3"} CRON
          %th{scope: "col", class: "px-6 py-3"} Последний запуск
          %th{scope: "col", class: "px-6 py-3", colspan: 2} Управление

        %tbody
          - @tasks.each do |t|
            %tr{class: 'hover:bg-blue-100 transition even:bg-gray-100 odd:bg-white border-b dark:bg-gray-800 dark:border-gray-700'}
              %td{class: "px-6 py-3"}
                = t['template'].name
                - if t['task']
                  %br
                  %small= t['task'].status == "enabled" ? 'Активно' : 'Отключено'

              - if t['task']
                %td{class: "px-6 py-3"}= t['task'].cron
                - if t['task'].last_enqueue_time
                  %td{class: "px-6 py-3"}
                    = t['task'].last_enqueue_time.localtime.strftime("%H:%M:%S %d.%m.%Y") 
                    %br
                    %small= "запущено #{distance_of_time_in_words(t['task'].last_enqueue_time.localtime, Time.now)} назад" 
                - else
                  %td{class: "px-6 py-3"}
              - else
                %td{class: "px-6 py-3"} - 
                %td{class: "px-6 py-3"} -
 
              %td{class: "px-6 py-3"}
                = link_to 'Выполнить', scheduler_task_action_path('enque', t['template'].id), remote: true
                %br
                %small 1 раз сейчас
              - if t['task'] and t['task'].status == 'enabled'
                %td{class: "px-6 py-3"}= link_to 'Остановить', scheduler_task_action_path('disable', t['template'].id)
              - else
                %td{class: "px-6 py-3"}= link_to 'В план', scheduler_task_action_path('enable', t['template'].id)

- if current_user.id == 1
  %div{class: "mx-auto px-4 py-4 md:pb-2 lg:px-8 "}
    %h2{class: 'text-xl mb-2 font-bold tracking-tight text-gray-900 place-items-center self-center place-self-center justify-items-center'} Все задания
    %table.w-full.px-4.py-6.text-sm.text-left.rtl:text-right.text-gray-800.dark:text-gray-400
      %thead{class: "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"}

        %tr
          %th{scope: "col", class: "px-6 py-3"} name
          %th{scope: "col", class: "px-6 py-3"} class
          %th{scope: "col", class: "px-6 py-3"} cron
          %th{scope: "col", class: "px-6 py-3"} source
          %th{scope: "col", class: "px-6 py-3"} args
          %th{scope: "col", class: "px-6 py-3"} status
          %th{scope: "col", class: "px-6 py-3"} enqueue_time

      %tbody
        - @jobs.each do |task|
          %tr{class: 'hover:bg-blue-100 transition even:bg-gray-100 odd:bg-white border-b dark:bg-gray-800 dark:border-gray-700'}
            %td{class: "px-6 py-3"}= task.name
            %td{class: "px-6 py-3"}= task.klass
            %td{class: "px-6 py-3"}= task.cron
            %td{class: "px-6 py-3"}= task.source
            %td{class: "px-6 py-3"}= task.args
            %td{class: "px-6 py-3"}= task.status
            %td{class: "px-6 py-3"}= task.last_enqueue_time.localtime.strftime("%H:%M:%S %d.%m.%Y") if task.last_enqueue_time