config/routes.rb
Rails.application.routes.draw do
  namespace :sale do 
    resources :reports
  end
  
  namespace :warehouse do
    get 'warehouse/index'
  end
  namespace :deliveries do
    get 'supply_schema/schema'
    get 'supply_schema/stats'
    get 'priorities/index'
    resources :scheduleds
    resources :scheduled_items
  end

  namespace :tariff do
    get 'tariffs/index'
    get 'tariff/index'
  end

  namespace :task_manager do
    resources :tasks
    resources :statuses
    resources :categories
  end

  resources :app_global_constants
  resources :sales_operations
  resources :sales
  resources :autoresponsers

  require 'sidekiq_unique_jobs/web'
  mount Sidekiq::Web => '/sidekiq', at: "/sidekiq"

  # Rails.application.routes.draw do
  resources :sale_reports
  namespace :sale do
    get 'sale_reports/csv/:id', to: 'reports#report_csv', as: 'report_csv'
  end
  patch 'nms/update_price/:id', to: 'nms#update_price', as: 'update_price'

  namespace :warehouse do
    get 'warehouse/index'
  end
  namespace :deliveries do
    get 'supply_schema/schema'
    get 'priorities/index'
    resources :scheduleds
    resources :scheduled_items
  end


  namespace :nm do
    resources :nm_customer_discounts
    resources :nm_customer_discounts
    resources :nm_comperitors
    resources :nm_group_competitors
    resources :nm_group_queries
    resources :nms
    patch 'nms/update_price/:id', to: 'nms#update_price', as: 'update_price'
    post '/competitor_action/:id', to: 'nms#competitor_action', as: 'nm_competitor_action'
    post 'nm_group_queries/:id/query_item_action', to: 'nm_group_queries#query_item_action', as: 'nm_group_queries_item_action'
    get 'nm_group_queries/update_nm_positions/:nm_id', to: 'nm_group_queries#update_nm_positions', as: 'nm_group_queries_update_nm_positions'

  end
  resources :app_global_constants
  resources :sales_operations
  resources :sales
  resources :autoresponsers
  # resources :promotion_managers
  #   mount Sidekiq::Web => "/sidekiq"
  #   get "job" => "job#index"
  #   get "job/email" => "job#email"
  #   get "job/post" => "job#delayed_post"
  #   get "job/long" => "job#long"
  #   get "job/crash" => "job#crash"
  #   get "job/bulk" => "job#bulk"
  # end

  namespace :income do 
    post "income/update_box_type/:id", to: "income#update_box_type", as: "box_update"
    resources :income
    get "planned", to: "planned#index"
    get "planned/archived", to: "planned#archived"
    get "planned/show/:id", to: "planned#show", as: "planned_show"
    get "planned/delete/:id", to: "planned#delete", as: "planned_delete"
    get "planned/create", to: "planned#create", as: "planned_create"
    post "planned/update/:income_id", to: "planned#update", as: "planned_update"
  end
  namespace :project do 
    resources :project_roles
    resources :projects
    post "projects/role/change", to: "projects#role_user_on_projects_action", as: "projects_role_user_on_projects_action"
    post "projects/set_as_current_project", to: "projects#set_as_current_project", as: "set_as_current_project"
    post "projects/settings/change", to: "projects#user_settings_update", as: "user_settings_update"

  end
  
  resources :delivery_methods

  resources :comissions
  namespace :advert do 
    resources :adverts

    get 'adverts/:id/advert_update_api', to: 'adverts#update_from_api', as: 'advert_update_api'
    get 'adverts/:id/start', to: 'adverts#start', as: 'advert_start'
    # get 'adverts/:id/stop', to: 'adverts#stop', as: 'advert_stop'
    get 'adverts/:id/pause', to: 'adverts#pause', as: 'advert_pause'
    post 'advert/adverts/set_cpm/:id', to: 'adverts#set_cpm', as: 'set_cpm'
    post 'advert/adverts/set_daily_budget_max/:id', to: 'adverts#set_daily_budget_max', as: 'set_daily_budget_max'
    get 'adverts/:id/:advert_action', to: 'adverts#advert_action', as: 'advert_action'
    post 'adverts/:id/cluster/set_forced_state/:cluster_id', to: 'adverts#cluster_set_forced_state', as: 'cluster_set_forced_state'
    get 'adverts/:id/keywords/flush_excluded_keyword', to: 'adverts#flush_excluded_keyword', as: 'flush_excluded_keyword'
    get 'adverts/:id/keywords/clear_bad_keywords', to: 'adverts#clear_bad_keywords', as: 'clear_bad_keywords'

    get '/advert/render_async_cluster_stats/:id/:cluster_id', to: "adverts#render_async_cluster_stats", as: 'render_async_cluster_stats'
    #  to 'advert#render_partial_advert_clusters_async' as 'render_partial_advert_clusters_async'
    
    resources :promotion_managers
    get 'promotion_manager/:id/setup', to: 'promotion_managers#setup', as: 'promotion_manager_setup'
    get 'promotion_manager/setup_all', to: 'promotion_managers#setup_all', as: 'promotion_manager_setup_all'
    get 'promotion_manager/:id/set_status/:status', to: 'promotion_managers#set_status', as: 'promotion_manager_set_status'
  end

  resources :events
  resources :orders
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', "passwords": 'users/passwords'}
  # devise_for :users, :as => :user_session
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboard#index", layouts: 'layouts'


  get "dashboard/stocks_history", to: "dashboard#stocks_history", layouts: 'layouts'
  get "dashboard/daily", to: "dashboard#daily", layouts: 'layouts'
  get "dashboard/trading", to: "dashboard#trading", layouts: 'layouts'
  get "dashboard/warehouse_balance", to: "dashboard#warehouse_balance", layouts: 'layouts'
  get "dashboard/stocks_planning", to: "dashboard#stocks_planning", layouts: 'layouts'
  get "dashboard/logistics_planning", to: "dashboard#logistics_planning", layouts: 'layouts'
  get "dashboard/sales_stats_by_district", to: "dashboard#sales_stats_by_district", layouts: 'layouts'
  get "dashboard/profit_by_current_stocks", to: "dashboard#profit_by_current_stocks", layouts: 'layouts'
  get "dashboard/nm_positions", to: "dashboard#nm_positions", layouts: 'layouts'
  get "dashboard/con_anal", to: "dashboard#con_anal", layouts: 'layouts'
  get "dashboard/weekly_orders", to: "dashboard#weekly_orders", layouts: 'layouts'
  get "dashboard/stocks_by_incomes", to: "dashboard#stocks_by_incomes"
  get "dashboard/nm/stats", to: "dashboard#nm_stats"



  get "scheduler/main", to: "scheduler#main", layouts: 'layouts'
  get "scheduler/task/:task_action/:id", to: "scheduler#task_action", layouts: 'layouts',  as: 'scheduler_task_action'

  # get "nms_queries/index", to: "nm_group_query#index", layouts: 'layouts'


  get "regions/regions", to: "regions#regions", layouts: 'layouts'
  get "regions/districts", to: "regions#districts", layouts: 'layouts'
  get "regions/district_warehouses", to: "regions#district_warehouses", layouts: 'layouts'

  
  #post 'nm_group_queries/:id/query_item_action', to: 'nm_group_queries#query_item_action', as: 'nm_group_queries_item_action'


  namespace :tariff do 
    resources :tariffs
    get "tariffs_active/index", to: "tariffs_active#index", layouts: 'layouts'
    get "tariffs_active/set/:id", to: "tariffs_active#set", layouts: 'layouts', as: 'tariffs_active_set'
    get "tariffs_active/unset/:id", to: "tariffs_active#unset", layouts: 'layouts', as: 'tariffs_active_unset'
  end


  get "pricing/index", to: "pricing#index", as: 'pricings'
  get "pricing/warehouses", to: "pricing#warehouses", as: 'pricing_wh'

  get "pricing/update_price/:nm_id", to: "pricing#update_price_item", as: 'pricings_update_prices_item'
  get "pricing/update_prices_all", to: "pricing#update_prices_all", as: 'pricings_update_prices_all'
  get "pricing/graph_prices_vs_sales/:nm_id", to: "pricing#graph_prices_vs_sales", as: 'pricing_price_vs_sales'
  get "pricing/graph_prices_vs_sales_data/:nm_id", to: "pricing#graph_prices_vs_sales_data", as: 'graph_prices_vs_sales_data'
  
  
end














  # 

app/views/layouts/header/_dropdown.haml
.relative{"data-controller"=>"dropdown", "data-action"=>"click->dropdown#toggle click@window->dropdown#hide"}
  %button.flex.items-center.gap-x-1.text-sm.font-semibold.leading-6.text-gray-100.hover:text-gray-300.rounded-md.px-4.py-2{"aria-expanded" => "false", :type => "button", :id => "dropdown-button"}
    = item_list[:name]
    %svg.h-5.w-5.flex-none.text-gray-300{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20"}
      %path{"clip-rule" => "evenodd", :d => "M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z", "fill-rule" => "evenodd"}
  /
    'Product' flyout menu, show/hide based on flyout menu state.
    
    Entering: "transition ease-out duration-200"
    From: "opacity-0 translate-y-1"
    To: "opacity-100 translate-y-0"
    Leaving: "transition ease-in duration-150"
    From: "opacity-100 translate-y-0"
    To: "opacity-0 translate-y-1"
  .hidden.absolute.-left-8.top-full.z-10.mt-3.overflow-hidden.rounded.bg-white.shadow-lg.ring-1{:class => "ring-gray-900/5", "data-dropdown-target"=>"menu"}
    - if current_user and current_user.project_id.to_i != admin_project_id.to_i
      - items = item_list[:items].select {|i| not i[:only_admin]} 
    - else
      - items = item_list[:items]
    - items.each do |hi|
      .group.text-nowrap.relative.flex.items-center.gap-x-6.rounded-lg.px-4.py-2.text-sm.leading-6.hover:bg-gray-50
        / .flex.h-11.w-11.flex-none.items-center.justify-center.rounded-lg.bg-gray-50.group-hover:bg-white
        /   %svg.h-6.w-6.text-gray-600.group-hover:text-indigo-600{"aria-hidden" => "true", :fill => "none", :stroke => "currentColor", "stroke-width" => "1.5", :viewbox => "0 0 24 24"}
        /     %path{:d => "M10.5 6a7.5 7.5 0 107.5 7.5h-7.5V6z", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
        /     %path{:d => "M13.5 10.5H21A7.5 7.5 0 0013.5 3v7.5z", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
        .flex-auto
          %a.block.text-gray-900{:href => "#{hi[:path]}"}
            = hi[:name]
            %span.absolute.inset-0
          / %p.mt-1.text-gray-600 Get a better understanding of your traffic

app/views/layouts/header/_dropdown_mobile.haml
.-mx-3{"data-controller"=>"dropdown", "data-action"=>"click->dropdown#toggle click@window->dropdown#hide"}
  %button.flex.w-full.items-center.justify-between.rounded-lg.py-2.pl-3.text-base.font-semibold.leading-7.text-gray-900.hover:bg-gray-50{:class => "pr-3.5", :type => "button", "aria-expanded" => "false", :type => "button", :id => "dropdown-button"}
    = item_list[:name]
    /
      Expand/collapse icon, toggle classes based on menu open state.
      
      Open: "rotate-180", Closed: ""
    %svg.h-5.w-5.flex-none{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20"}
      %path{"clip-rule" => "evenodd", :d => "M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z", "fill-rule" => "evenodd"}
  / 'Product' sub-menu, show/hide based on menu state.
  #disclosure-1.mt-2.space-y-2{"data-dropdown-target"=>"menu"}
    - if current_user and current_user.project_id.to_i != admin_project_id.to_i
      - items = item_list[:items].select {|i| not i[:only_admin]} 
    - else
      - items = item_list[:items]
    - items.each do |hi|
      %a.block.rounded-lg.py-2.pl-6.pr-3.text-sm.font-semibold.leading-7.text-gray-900.hover:bg-gray-50{:href => "#{hi[:path]}"}= hi[:name]
  

app/views/layouts/header/_main.haml
%nav.bg-blue-600.text-gray-100.mx-auto.flex.items-center.justify-between.p-3.shadow.lg:px-8{"aria-label" => "Global"}
  .flex.lg:flex-1
    %a{:class => "-m-1.5 p-1.5 hover:text-sky-500", :href => "#{root_path}"}
      %span PumPurum
      / %img.h-8.w-auto{:alt => "", :src => "https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"}/
  .flex.lg:hidden
    %button.inline-flex.items-center.justify-center.rounded-md.text-gray-700{:class => "-m-2.5 p-2.5", :type => "button", 'data-action'=>'click->toggle#toggle touch->toggle#toggle'}
      %span.sr-only Open main menu
      %svg.h-6.w-6.text-gray-100.hover:text-sky-500{"aria-hidden" => "true", :fill => "none", :stroke => "currentColor", "stroke-width" => "1.5", :viewbox => "0 0 24 24"}
        %path{:d => "M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
  .hidden.lg:flex.lg:gap-x-12

    = render 'layouts/header/dropdown', {item_list: header_menu_item_list[:dashboard]}
    = render 'layouts/header/dropdown', {item_list: header_menu_item_list[:trading]}
    = render 'layouts/header/dropdown', {item_list: header_menu_item_list[:incomes]}
    = render 'layouts/header/dropdown', {item_list: header_menu_item_list[:log]}
    = render 'layouts/header/dropdown', {item_list: header_menu_item_list[:nsi]}

  .hidden.lg:flex.lg:flex-1.lg:justify-end
    .group.relative.flex.items-center.gap-x-6.rounded-lg.p-4.text-sm.leading-6.hover
      - if user_signed_in?
        = render 'layouts/header/dropdown', {item_list: header_menu_item_list[:project]}
        %a.block.font-semibold.text-gray-100.hover:text-sky-500{:href => "#{destroy_user_session_path}"}
          %span{"aria-hidden" => "true"} Выйти
        / = link_to "#{current_user.email} (ID #{current_user.id})", edit_user_registration_path
        / %ul.dropdown.menu{"data-dropdown-menu"=>"true"}
        /   %li= link_to "#{current_user.email} (ID #{current_user.id})", edit_user_registration_path
        /   %li= link_to "Выйти", destroy_user_session_path, :method => :delete
        /   - if current_user.id == 1
        /     %li= link_to "Константы", app_global_constants_path
      - else
        %a.block.font-semibold.text-gray-100{:href => "#{new_user_session_path}"}
          %span.hover:text-sky-500{"aria-hidden" => "true"} Войти
        %a.block.font-semibold.text-gray-100{:href => "#{new_user_registration_path}"}
          %span.hover:text-sky-500{"aria-hidden" => "true"} Регистрация

app/views/layouts/header/_mobile.haml
/ Mobile menu, show/hide based on menu open state.
.lg:hidden.hidden{"aria-modal" => "true", :role => "dialog", 'data-toggle-target'=>'toggleable'}
  / Background backdrop, show/hide based on slide-over state.
  .fixed.inset-0.z-10{}
  .fixed.inset-y-0.right-0.z-10.w-full.overflow-y-auto.bg-white.px-6.py-6.sm:max-w-sm.sm:ring-1{:class => "sm:ring-gray-900/10"}
    .flex.items-center.justify-between
      %a{:class => "-m-1.5 p-1.5", :href => "#"}
        %span.sr-only PumPurum
        / %img.h-8.w-auto{:alt => "", :src => "https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"}/
      %button.rounded-md.text-gray-700{:class => "-m-2.5 p-2.5", :type => "button", 'data-action'=>'click->toggle#toggle touch->toggle#toggle'}
        %span.sr-only Close menu
        %svg.h-6.w-6{"aria-hidden" => "true", :fill => "none", :stroke => "currentColor", "stroke-width" => "1.5", :viewbox => "0 0 24 24"}
          %path{:d => "M6 18L18 6M6 6l12 12", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
    .mt-6.flow-root
      .-my-6.divide-y{:class => "divide-gray-500/10"}
        .space-y-2.py-6
          = render 'layouts/header/dropdown_mobile', {item_list: header_menu_item_list[:dashboard]}
          = render 'layouts/header/dropdown_mobile', {item_list: header_menu_item_list[:trading]}
          = render 'layouts/header/dropdown_mobile', {item_list: header_menu_item_list[:log]}
          = render 'layouts/header/dropdown_mobile', {item_list: header_menu_item_list[:incomes]}
          = render 'layouts/header/dropdown_mobile', {item_list: header_menu_item_list[:nsi]}
          = render 'layouts/header/dropdown_mobile', {item_list: header_menu_item_list[:project]}


          / %a.-mx-3.block.rounded-lg.px-3.py-2.text-base.font-semibold.leading-7.text-gray-900.hover:bg-gray-50{:href => "#"} Features
          / %a.-mx-3.block.rounded-lg.px-3.py-2.text-base.font-semibold.leading-7.text-gray-900.hover:bg-gray-50{:href => "#"} Marketplace
          / %a.-mx-3.block.rounded-lg.px-3.py-2.text-base.font-semibold.leading-7.text-gray-900.hover:bg-gray-50{:href => "#"} Company
        .py-6
          %a.-mx-3.block.rounded-lg.px-3.text-base.font-semibold.leading-7.text-gray-900.hover:bg-gray-50{:class => "py-2.5", :href => "#"} Log in